#!/usr/bin/env bash
# Rebuild web/cards.dart.js from the Dart 1.x sources in web/.
#
# The game is pre-Dart-2 (SDK 1.24.3, box2d 0.1.7 — NOT the 0.4.0 the stale
# pubspec.lock claims; 0.1.7 is the version whose API (Body.createFixture,
# 2-arg PolygonShape.setAsBox) matches the sources and the shipped artifact).
# The SDK and the pinned pub packages are cached under ~/.cache/twocubes-build
# and fetched on first run; afterwards the build is fully offline.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
B="${TWOCUBES_BUILD_CACHE:-$HOME/.cache/twocubes-build}"
SDK_URL="https://storage.googleapis.com/dart-archive/channels/stable/release/1.24.3/sdk/dartsdk-linux-x64-release.zip"

mkdir -p "$B/pkg"

if [ ! -x "$B/dart-sdk/bin/dart2js" ]; then
    echo "Fetching Dart SDK 1.24.3..."
    curl -sSLo "$B/sdk.zip" "$SDK_URL"
    unzip -q "$B/sdk.zip" -d "$B" && rm "$B/sdk.zip"
fi

fetch_pkg() { # name version
    if [ ! -f "$B/pkg/$1-$2/pubspec.yaml" ]; then
        echo "Fetching package $1 $2..."
        mkdir -p "$B/pkg/$1-$2"
        curl -sSL "https://pub.dev/api/archives/$1-$2.tar.gz" | tar -xz -C "$B/pkg/$1-$2"
    fi
}
# NOTE: pubspec.lock is stale — it names box2d 0.4.0 / vector_math 2.0.7,
# whose APIs don't match the sources (Body.createFixture, chainable
# Vector2.sub). These are the era-correct versions the shipped artifact was
# actually built against.
fetch_pkg animation 0.5.24
fetch_pkg box2d 0.1.7
fetch_pkg browser 0.10.0+3
fetch_pkg sprintf 4.0.2
fetch_pkg vector_math 1.4.7
fetch_pkg quiver 0.22.0

# The original team shipped box2d with a hand-added World.setGravity (the
# stock 0.1.7 field is private and has no setter; the shipped cards.dart.js
# contains the method). Re-apply that one-line patch after fetching.
WORLD="$B/pkg/box2d-0.1.7/lib/src/dynamics/world.dart"
if ! grep -q "void setGravity" "$WORLD"; then
    sed -i 's|^  final Vector2 _gravity;$|  final Vector2 _gravity;\n\n  /// Two Cubes local patch (tools/build-dart.sh): per-level gravity.\n  void setGravity(Vector2 gravity) {\n    _gravity.setFrom(gravity);\n  }|' "$WORLD"
    grep -q "void setGravity" "$WORLD" || { echo "box2d setGravity patch failed"; exit 1; }
fi

cat > "$ROOT/.packages" <<EOF
# Dart 1.x package resolution, generated by tools/build-dart.sh. Not committed.
Cards:web/
animation:$B/pkg/animation-0.5.24/lib/
box2d:$B/pkg/box2d-0.1.7/lib/
browser:$B/pkg/browser-0.10.0+3/lib/
sprintf:$B/pkg/sprintf-4.0.2/lib/
vector_math:$B/pkg/vector_math-1.4.7/lib/
quiver:$B/pkg/quiver-0.22.0/lib/
EOF

"$B/dart-sdk/bin/dart2js" --packages="$ROOT/.packages" \
    -o "$ROOT/web/cards.dart.js" "$ROOT/web/cards.dart" "$@"

# dart2js side products nobody serves or commits.
rm -f "$ROOT/web/cards.dart.js.deps" "$ROOT/web/cards.dart.js.map"
echo "Built web/cards.dart.js"
